version: '3.8'

services:
  ffc-sfi-eligibility:
    build:
      context: .
      target: production
    image: ffc-sfi-eligibility
    container_name: ffc-sfi-eligibility
    environment:
      ELIGIBILITY_CHANGED_TOPIC_ADDRESS: ${ELIGIBILITY_CHANGED_TOPIC_ADDRESS:-notset}
      ELIGIBILITY_CHECKER_SUBSCRIPTION_ADDRESS: ${ELIGIBILITY_CHECKER_SUBSCRIPTION_ADDRESS:-notset}
      MESSAGE_QUEUE_HOST: ${MESSAGE_QUEUE_HOST:-notset}
      MESSAGE_QUEUE_PASSWORD: ${MESSAGE_QUEUE_PASSWORD:-notset}
      MESSAGE_QUEUE_USER: ${MESSAGE_QUEUE_USER:-notset}
      UPDATE_ELIGIBILIY_QUEUE_ADDRESS: ${UPDATE_ELIGIBILIY_QUEUE_ADDRESS:-notset}
