version: '3.8'

services:
  ffc-sfi-eligibility:
    build:
      context: .
      target: production
    image: ffc-sfi-eligibility
    container_name: ffc-sfi-eligibility
    environment:
      ELIGIBILITY_CHANGED_TOPIC_ADDRESS: ${ELIGIBILITY_CHANGED_TOPIC_ADDRESS:-notset}
      ELIGIBILITY_CHANGED_SUBSCRIPTION_ADDRESS: ${ELIGIBILITY_CHANGED_SUBSCRIPTION_ADDRESS:-notset}
      SERVICE_BUS_HOST: ${SERVICE_BUS_HOST:-notset}
      SERVICE_BUS_PASSWORD: ${SERVICE_BUS_PASSWORD:-notset}
      SERVICE_BUS_USER: ${SERVICE_BUS_USER:-notset}
      UPDATE_ELIGIBILITY_QUEUE_ADDRESS: ${UPDATE_ELIGIBILITY_QUEUE_ADDRESS:-notset}
